apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: chrys789621/devops-api:2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: api_example
            - name: DB_USERNAME
              value: root
            - name: DB_USERNAME_PASSWORD
              value: root
