apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: chrys789621/devops-api:2.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: test

            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: test
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: devops
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
