name: CI/CD DevOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t chrys789621/devops-api:latest ./2-docker/Node-Express-REST-API-MySQL-JS-Example

      - name: Login Docker Hub
        run: |
          echo "hmop667" | docker login -u chrys789621 --password-stdin

      - name: Push Docker image
        run: |
          docker push chrys789621/devops-api:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f 3-kubernetes/manifests/
          kubectl rollout restart deployment api -n devops
