name: CI/CD DevOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug
        run: |
          pwd
          ls -R

      - name: Build Docker image
        working-directory: 2-docker/Node-Express-REST-API-MySQL-JS-Example
        run: docker build -t devops-api .

      - name: Test container
        run: docker run -d -p 3000:3000 devops-api || true
